[simple.center-ops]
ligGroup =  'center-ops'
desc = 'Vertically align some of the operators (like `*`) to the center position it is before or after a "center" operator (like `+`)'

[simple.arrow]
ligGroup =  "arrow"
desc = 'Enable ligation set that forms arrows'

[simple.arrow2]
ligGroup =  "arrow2"
desc = 'Enable ligation for more arrows, like `>>=`'

[simple.trig]
ligGroup =  "trig"
desc = 'Enable ligation for `<|`, `|>` , `<||`, and other bar-and-angle-bracket symbols'

[simple.eqeqeq]
ligGroup =  "eqeqeq"
desc = 'Enable special ligation for `===` with triple lines'

[simple.eqeq]
ligGroup =  "eqeq"
desc = 'Enable ligation for `==` and `===`'

[simple.ineq]
ligGroup =  "ineq"
desc = 'Enable ligation for `<=` and `>=`'

[simple.exeqeq]
ligGroup =  "exeqeq"
desc = 'Enable special ligation for `!==` with triple lines'

[simple.exeqeq-dotted]
ligGroup =  "exeqeq-dotted"
desc = 'Enable special ligation for `!==` with triple lines, and a dot at below for distinction'

[simple.eqexeq]
ligGroup =  "eqexeq"
desc = 'Enable special ligation for `=!=` with triple lines'

[simple.eqexeq-dotted]
ligGroup =  "eqexeq-dotted"
desc = 'Enable special ligation for `=!=` with triple lines and a dot at below for distinction'

[simple.eqexeq-dl]
ligGroup =  "eqexeq-dl"
desc = 'Enable special ligation for `=!=` with double lines'

[simple.eqexeq-dl-dotted]
ligGroup =  "eqexeq-dl-dotted"
desc = 'Enable special ligation for `=!=` with double lines, and a dot at below for distinction'

[simple.exeq]
ligGroup =  "exeq"
desc = 'Enable ligation for `!=` and `!==`'

[simple.exeq-dotted]
ligGroup =  "exeq-dotted"
desc = 'Enable ligation for `!=` and `!==` with a dot at below for distinction'

[simple.tildeeq]
ligGroup =  "tildeeq"
desc = 'Enable ligation for `~=` as inequality'

[simple.eqslasheq]
ligGroup = "eqslasheq"
desc = 'Enable special triple-line ligation for `=/=` as inequality'

[simple.slasheq]
ligGroup = "slasheq"
desc = 'Enable ligation for `/=` and `=/=` as inequality'

[simple.ltgt-ne]
ligGroup = "ltgt-ne"
desc = 'Enable ligation for `<>` as inequality'

[simple.ltgt-diamond]
ligGroup = "ltgt-diamond"
desc = 'Enable ligation for `<>` as diamond'

[simple.brst]
ligGroup = "brst"
desc = 'Center asterisk in `(*` and `*)`'

[simple.plusplus]
ligGroup =  "plusplus"
desc = 'Enable ligation for `++` and further plus-chaining'

[simple.kern-dotty]
ligGroup =  "kern-dotty"
desc = 'Move connecting dotty punctuations closer, like for `::`, `:::` and `...`'

[simple.logic]
ligGroup =  "logic"
desc = 'Enable ligation for `/\` and `\/`'

[simple.llgg]
ligGroup =  "llgg"
desc = 'Enable ligation for `<<`, `>>` and other angle-bracket chaining'

[simple.llggeq]
ligGroup =  "llggeq"
desc = 'Enable ligation for `<<=`, `>>=` as shift operator'

[simple.dot-as-operator]
ligGroup =  "dot-oper"
desc = 'Treat dot (`.`) as operator and perform chained centering'

[simple.lteq-as-arrow]
ligGroup =  "arrowZALE"
desc = 'Treat `<=` as arrow'

[simple.gteq-as-co-arrow]
ligGroup =  "arrowZAGE"
desc = 'Treat `>=` as co-arrow'

[simple.html-comment]
ligGroup =  "html-comment"
desc = 'Enable ligation for `<!--` and `<!---`'

[simple.colon-greater-as-colon-arrow]
ligGroup = "colon-greater"
desc = 'Transform `:>` into `:` and a narrow arrow'

[simple.brace-bar]
ligGroup = 'brace-bar'
desc = 'Enable ligation for `{|` and `|}`'

[simple.brack-bar]
ligGroup = 'brack-bar'
desc = 'Enable ligation for `[|` and `|]`'

[simple.connected-underscore]
ligGroup = 'connected-underscore'
desc = 'Make contiguous underscores (like `__`) connected'

[simple.connected-number-sign]
ligGroup = 'connected-number-sign'
desc = 'Make contiguous number signs (like `##`) connected'

[simple.connected-tilde-as-wave]
ligGroup = 'connected-tilde-as-wave'
desc = 'Make contiguous ASCII tildes (like `~~`) connected as a wave line'

[simple.connected-hyphen-as-solid-line]
ligGroup = 'connected-hyphen-as-solid-line'
desc = 'Make contiguous hyphen-minuses (like `--`) connected as a straight solid line'

[simple.connected-hyphen-as-semi-dashed-line]
ligGroup = 'connected-hyphen-as-semi-dashed-line'
desc = 'Make contiguous hyphen-minuses (like `--`) connected as a straight semi-dashed line, identifying each hyphen component'

###################################################################################################

# This feature is on by default by many software
[composite.default-calt]
tag     = 'calt'
buildup = ['center-ops', 'arrow', 'html-comment', 'trig', 'llgg', 'llggeq', 'eqeq', 'exeq', 'ineq', 'plusplus', 'kern-dotty']
brief   = 'Default'
desc    = 'Default setting in text editors'
readmeDesc = 'Inherit default ligation set'

[composite.dlig]
tag     = 'dlig'
buildup = ['center-ops', 'arrow', 'html-comment', 'trig', 'arrow2', 'llgg', 'eqeq', 'exeq', 'ineq', 'ltgt-diamond', 'plusplus', 'kern-dotty', 'dot-as-operator', 'logic', 'brst', 'brace-bar', 'brack-bar', 'connected-underscore', 'connected-number-sign', 'connected-tilde-as-wave', 'connected-hyphen-as-semi-dashed-line']
brief   = 'Discretionary'
desc    = 'Discretionary ligatures'

[composite.clike]
tag     = 'CLIK'
buildup = ['center-ops', 'arrow', 'html-comment', 'trig', 'llgg', 'llggeq', 'eqeqeq', 'eqeq', 'exeqeq', 'exeq', 'ineq', 'plusplus', 'kern-dotty']
desc    = 'C-Like'

[composite.javascript]
tag     = 'JSPT'
buildup = ['center-ops', 'arrow', 'html-comment', 'trig', 'llgg', 'llggeq', 'eqeqeq', 'eqeq', 'exeqeq', 'exeq', 'ineq', 'plusplus', 'kern-dotty']
desc    = 'JavaScript'

[composite.php]
tag     = 'PHPX'
buildup = ['center-ops', 'arrow', 'html-comment', 'trig', 'llgg', 'llggeq', 'eqeqeq', 'eqeq', 'exeqeq', 'exeq', 'ineq', 'plusplus', 'kern-dotty']
desc    = 'PHP'

[composite.ml]
tag     = 'MLXX'
buildup = ['center-ops', 'arrow', 'trig', 'eqeq', 'ltgt-ne', 'ineq', 'brst', 'plusplus', 'logic']
desc    = 'ML'

[composite.fsharp]
tag     = 'FSHP'
buildup = ['center-ops', 'arrow', 'trig', 'eqeq', 'ltgt-ne', 'ineq', 'brst', 'plusplus', 'logic']
desc    = 'F#'

[composite.fstar]
tag     = 'FSTA'
buildup = ['center-ops', 'arrow', 'trig', 'eqeq', 'ltgt-ne', 'eqeqeq', 'eqexeq', 'ineq', 'brst', 'plusplus', 'logic']
desc    = 'F*'

[composite.haskell]
tag     = 'HSKL'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'slasheq', 'ineq', 'ltgt-diamond', 'plusplus', 'dot-as-operator', 'kern-dotty', 'logic']
desc    = 'Haskell'

[composite.idris]
tag     = 'IDRS'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'slasheq', 'ineq', 'ltgt-diamond', 'plusplus', 'dot-as-operator', 'kern-dotty', 'logic']
desc    = 'Idris'

[composite.elm]
tag     = 'ELMX'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'slasheq', 'ineq', 'ltgt-diamond', 'plusplus', 'dot-as-operator', 'kern-dotty', 'logic']
desc    = 'Elm'

[composite.purescript]
tag     = 'PURS'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'slasheq', 'ineq', 'ltgt-diamond', 'plusplus', 'dot-as-operator', 'kern-dotty', 'logic']
desc    = 'PureScript'

[composite.swift]
tag     = 'SWFT'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'exeq', 'ineq', 'ltgt-diamond', 'plusplus']
desc    = 'Swift'

[composite.coq]
tag     = 'COQX'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'ltgt-ne', 'ineq', 'plusplus', 'dot-as-operator', 'logic', 'brst']
desc    = 'Coq'

[composite.matlab]
tag     = 'MTLB'
buildup = ['center-ops', 'arrow', 'html-comment', 'trig', 'llgg', 'eqeq', 'tildeeq', 'ineq', 'plusplus', 'kern-dotty']
desc    = 'Matlab'

[composite.verilog]
tag     = 'VRLG'
buildup = ['center-ops', 'arrow', 'html-comment', 'trig', 'llgg', 'llggeq', 'eqeqeq', 'eqeq', 'exeqeq', 'exeq', 'plusplus', 'kern-dotty', 'brst']
desc    = 'Verilog'

[composite.wolfram]
tag     = 'WFLM'
buildup = ['center-ops', 'arrow', 'trig', 'ltgt-diamond', 'eqeq', 'exeq', 'eqexeq-dl', 'ineq', 'brst', 'plusplus', 'logic', 'colon-greater-as-colon-arrow']
brief   = 'Wolfram'
desc    = 'Wolfram Language (Mathematica)'
