# https://typeof.net/Iosevka/customizer?cv-capital-j=serifless&cv-capital-k=symmetric-touching-bottom-right-serifed&cv-capital-q=crossing&cv-a=single-storey-tailed&cv-d=tailed-serifless&cv-k=symmetric-touching-bottom-right-serifed&cv-t=flat-hook&cv-u=tailed&cv-w=straight-flat-top&cv-y=straight-turn&cv-lower-lambda=straight-turn&cv-cyrl-capital-ka=curly-serifless&cv-cyrl-capital-u=cursive-flat-hook&cv-cyrl-capital-ze=unilateral-inward-serifed&cv-cyrl-en=tailed-serifless&cv-cyrl-ka=curly-serifless&cv-cyrl-yeri=round&cv-cyrl-yery=round&cv-cyrl-ze=unilateral-inward-serifed&cv-one=base&cv-four=closed&cv-six=open-contour&cv-eight=two-circles&cv-asterisk=hex-high&cv-paragraph-sign=low&cv-brace=straight&cv-at=fourfold&cv-percent=rings-continuous-slash&cv-bar=force-upright&cv-lig-ltgteq=slanted&ligations=clike

# [buildPlans.iosevnya]            # <iosevnya> is your plan name
# family = "Iosevnya"              # Font menu family name
# spacing = "normal"               # Optional; Values: `normal`, `term`, `fontconfig-mono`, or `fixed`
# serifs = "sans"                  # Optional; Values: `sans` or `slab`

[buildPlans.iosevnya]
family           = "Iosevnya"
spacing          = "normal"
serifs           = "sans"
no-cv-ss         = true
export-glyph-names = true

###################################################################################################
# Configure variants

[buildPlans.iosevnya.variants.design]
capital-j     = "serifless"
capital-k     = "symmetric-touching-bottom-right-serifed"
capital-q     = "crossing"
a             = "single-storey-tailed"
d             = "tailed-serifless"
k             = "symmetric-touching-bottom-right-serifed"
t             = "flat-hook"
u             = "tailed"
w             = "straight-flat-top"
y             = "straight-turn"
lower-lambda  = "straight-turn"
cyrl-capital-ze = "unilateral-inward-serifed"
cyrl-ze       = "unilateral-inward-serifed"
cyrl-capital-ka = "curly-serifless"
cyrl-ka       = "curly-serifless"
cyrl-en       = "tailed-serifless"
cyrl-capital-u = "cursive-flat-hook"
cyrl-yeri     = "round"
cyrl-yery     = "round"
one           = "base"
four          = "closed"
six           = "open-contour"
eight         = "two-circles"
asterisk      = "hex-high"
paragraph-sign = "low"
brace         = "straight"
at            = "fourfold"
percent       = "rings-continuous-slash"
bar           = "force-upright"
lig-ltgteq    = "slanted"

[buildPlans.iosevnya.variants.italic]
i = "serifed-flat-tailed"
l = "serifed-flat-tailed"
q = "tailed"

# Optional; Whether to inherit a `ss##` variant
# [buildPlans.iosevnya.variants]
# inherits = "ss01"

# Optional; Configure single character's variant
# [buildPlans.iosevnya.variants.design]
# g = 'single-storey'

# Optional; Configure single character's variant for Upright and Oblique; Overrides [design]
# [buildPlans.iosevnya.variants.upright]
# i = 'zshaped'
# l = 'zshaped'

# Optional; Configure single character's variant for Italic only; Overrides [design]
# [buildPlans.iosevnya.variants.italic]
# i = 'tailed-serifed'
# l = 'tailed-serifed'

# End variant section
###################################################################################################

###################################################################################################
# Configure ligations

# [buildPlans.iosevnya.ligations]
# inherits = "default-calt"   # Optional; inherits an existing ligation set
# disables = []               # Optional; disable specific ligation groups, overrides inherited ligation set
# enables  = []               # Optional; enable specific ligation groups, overrides inherited ligation set

[buildPlans.iosevnya.ligations]
inherits = "clike"
enables = ["arrow2", "brst", "connected-number-sign", "eqexeq-dotted", "ltgt-diamond"]

# End ligation section
###################################################################################################


###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#             and "shape" properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.

[buildPlans.iosevnya.weights.thin]
shape = 100
menu = 100
css = 100
[buildPlans.iosevnya.weights.extralight]
shape = 200
menu = 200
css = 200
[buildPlans.iosevnya.weights.light]
shape = 300
menu = 300
css = 300
[buildPlans.iosevnya.weights.regular]
shape = 400
menu = 400
css = 400
[buildPlans.iosevnya.weights.medium]
shape = 500
menu = 500
css = 500
[buildPlans.iosevnya.weights.semibold]
shape = 600
menu = 600
css = 600
[buildPlans.iosevnya.weights.bold]
shape = 700
menu = 700
css = 700
[buildPlans.iosevnya.weights.extrabold]
shape = 800
menu = 800
css = 800
[buildPlans.iosevnya.weights.black]
shape = 900
menu = 900
css = 900

# [buildPlans.iosevnya.weights.regular]
# shape = 400  # Weight for glyph shapes.
# menu  = 400  # Weight for the font's names.
# css   = 400  # Weight for webfont CSS.

# [buildPlans.iosevnya.weights.book]
# shape = 450
# menu  = 450  # Use 450 here to name the font's weight "Book"
# css   = 450

# [buildPlans.iosevnya.weights.bold]
# shape = 700
# menu  = 700
# css   = 700

# End weight section
###################################################################################################

###################################################################################################
# Override default building slope sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slopes would be built.

[buildPlans.iosevnya.slopes]
upright = "normal"
italic = "italic"
# oblique = "oblique"

# End slope section
###################################################################################################

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports numbers between 434 and 664 (inclusive),
#             while "menu" only supports integers between 1 and 9 (inclusive).
#             The "shape" parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#             width are equal to, or a simple multiple of the unit width.
#             If you decide to use custom widths you have to define all the widths you plan to use,
#             otherwise they will not be built.

[buildPlans.iosevnya.widths.normal]
shape = 500
menu = 5
css = "normal"

# [buildPlans.iosevnya.widths.normal]
# shape = 500        # Unit Width, measured in 1/1000 em.
# menu  = 5          # Width grade for the font's names.
# css   = "normal"   # "font-stretch' property of webfont CSS.

# [buildPlans.iosevnya.widths.extended]
# shape = 600
# menu  = 7
# css   = "expanded"

# End width section
###################################################################################################

###################################################################################################
# Character Exclusion
# Specify character ranges in the section below to exclude certain characters from the font being
# built. Remove this section when this feature is not needed.

# [buildPlans.iosevnya.exclude-chars]
# ranges = [[10003, 10008]]

# End character exclusion
###################################################################################################

###################################################################################################
# Compatibility Ligatures
# Certain applications like Emacs does not support proper programming liagtures provided by
# OpenType, but can support ligatures provided by PUA codepoints. Therefore you can edit the
# following section to build PUA characters that are generated from the OpenType ligatures.
# Remove this section when compatibility ligatures are not needed.

# [[buildPlans.iosevnya.compatibility-ligatures]]
# unicode = 57600 # 0xE100
# featureTag = 'calt'
# sequence = '<*>'

# End compatibility ligatures section
###################################################################################################

###################################################################################################
# Metric overrides
# Certain metrics like line height (leading) could be overridden in your build plan file.
# Edit the values to change the metrics. Remove this section when overriding is not needed.

# [buildPlans.iosevnya.metric-override]
# leading = 1250
# winMetricAscenderPad = 0
# winMetricDescenderPad = 0
# powerlineScaleY = 1
# powerlineScaleX = 1
# powerlineShiftY = 0
# powerlineShiftX = 0

# End metric override section
###################################################################################################

[collectPlans.iosevnya]
from = ["iosevnya"]
